import type { LocationDef, MapTheme } from './map-types.ts';

export const TOWN_LOCATIONS: LocationDef[] = [
  {
    id: 'tavern',
    name: 'Tavern',
    icon: '🍺',
    zone: 'town',
    position: { x: 1, y: 3 },
    enterable: true,
    requiresLevel: 1,
    description: 'A friendly tavern where you can chat with the AI bartender.',
    restrictInBattle: false,
    shortcutKey: 'H',
  },
  {
    id: 'shopping_district',
    name: 'Shopping District',
    icon: '🏪',
    zone: 'town',
    position: { x: 7, y: 2 },
    enterable: true,
    requiresLevel: 1,
    description: 'The commercial hub with 7 specialty shops.',
    restrictInBattle: true,
    shortcutKey: 'S',
  },
  {
    id: 'stasis_chamber',
    name: 'Stasis Chamber',
    icon: '⏸️',
    zone: 'town',
    position: { x: 8, y: 6 },
    enterable: true,
    requiresLevel: 1,
    description: 'Time freezes here. A space for deep thinking and Plan Mode.',
    restrictInBattle: false,
    shortcutKey: 'P',
  },
  {
    id: 'guild_hall',
    name: 'Guild Hall',
    icon: '🏛️',
    zone: 'town',
    position: { x: 4, y: 1 },
    enterable: true,
    requiresLevel: 1,
    description: 'Worktree management center and battle monitoring hub.',
    restrictInBattle: false,
    shortcutKey: 'G',
  },
  {
    id: 'player_home',
    name: 'Player Home',
    icon: '🏠',
    zone: 'town',
    position: { x: 4, y: 6 },
    enterable: true,
    requiresLevel: 1,
    description: 'Rest, save, and adjust settings in your personal space.',
    restrictInBattle: true,
    shortcutKey: 'R',
  },
  {
    id: 'training_ground',
    name: 'Training Ground',
    icon: '⚔️',
    zone: 'town',
    position: { x: 1, y: 6 },
    enterable: true,
    requiresLevel: 1,
    description: 'Practice and test skills without consuming resources.',
    restrictInBattle: true,
    shortcutKey: 'T',
  },
  {
    id: 'library',
    name: 'Library',
    icon: '📚',
    zone: 'town',
    position: { x: 7, y: 5 },
    enterable: true,
    requiresLevel: 3,
    description: 'Browse and install MCP tools and extensions.',
    restrictInBattle: true,
    shortcutKey: 'L',
  },
];

export const BUILT_IN_THEMES: MapTheme[] = [
  {
    name: 'classic',
    cssClass: 'classic',
    colors: {
      background: '#F5F5DC',
      ground: '#8FBC8F',
      building: '#D2B48C',
      buildingHover: '#C4A882',
      text: '#2C3E50',
      accent: '#4A90E2',
      statusBar: '#3C3C3C',
    },
  },
  {
    name: 'dark',
    cssClass: 'dark',
    colors: {
      background: '#1e1e1e',
      ground: '#2d2d30',
      building: '#3c3c3c',
      buildingHover: '#4c4c4c',
      text: '#d4d4d4',
      accent: '#569cd6',
      statusBar: '#252526',
    },
  },
];
