export const CONTENT_TYPE = {
  markdown: 'text/markdown',
  html: 'text/html',
  css: 'text/css',
  xml: 'text/xml',
  svg: 'image/svg+xml',
  pdf: 'application/pdf',
  png: 'image/png',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  webp: 'image/webp',
  ico: 'image/x-icon',
  woff: 'font/woff',
  woff2: 'font/woff2',
  ttf: 'font/ttf',
  eot: 'application/vnd.ms-fontobject',
  otf: 'font/otf',
  zip: 'application/zip',
  gz: 'application/gzip',
  tar: 'application/x-tar',
  plain: 'text/plain',
} as const;
